server.servlet.context-path=/notification-service
server.port=8083
spring.application.name=notification-service
spring.sleuth.messaging.jms.enabled=false



# JWT
application.security.jwt.secret-key=404E635277666A586E3272357538782F413F4428472B4B6250645367566B5970

# =========================
# DATASOURCE
# =========================
db.host=localhost
db.port=5432
db.name=notification_db

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://${db.host}:${db.port}/${db.name}
spring.datasource.username=postgres
spring.datasource.password=12345
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
spring.datasource.hikari.minimum-idle=0
spring.datasource.hikari.maximum-pool-size=30
spring.datasource.hikari.connection-test-query=SELECT 1

# =========================
# RABBITMQ
# =========================
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=admin
spring.rabbitmq.password=123abc

# =========================
# EMAIL (GMAIL EXAMPLE)
# =========================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=setiawan.df@gmail.com
spring.mail.password=aawdjuxxbgyfniao
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true



